DROP DATABASE IF EXISTS leaguedb;
CREATE DATABASE leaguedb;
USE leaguedb;

CREATE TABLE champ (
    champ_id MEDIUMINT UNSIGNED AUTO_INCREMENT NOT NULL,
    champName VARCHAR(20) NOT NULL,
    champTitle VARCHAR(30) NOT NULL,
    champRole VARCHAR(20) NOT NULL,
    champClass VARCHAR(20) NOT NULL,
    champType VARCHAR(20) NOT NULL,
    date_creamted TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT pk_champ_id PRIMARY KEY (champ_id)
);